CC = gcc

all: 
	$(CC) ./1/main.c ./1/hash.c -o ./1/q1.o
	$(CC) ./2/main.c ./2/hash.c -o ./2/q2.o
	$(CC) ./3/main.c ./3/heap.c -o ./3/q3.o
	$(CC) ./4/main.c ./4/heap.c -o ./4/q4.o

q1:
	$(CC) ./1/main.c ./1/hash.c -o ./1/q1.o

q2:
	$(CC) ./2/main.c ./2/hash.c -o ./2/q2.o

q3:
	$(CC) ./3/main.c ./3/heap.c -o ./3/q3.o

q4:
	$(CC) ./4/main.c ./4/heap.c -o ./4/q4.o
	
clean: 
	rm -rf ./*/*.o
	
